services:
  postgres-auth:
    image: postgres:12-alpine
    restart: unless-stopped
    container_name: postgres-auth
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: development_pass
      POSTGRES_DB: auth-api
    volumes:
      - auth_api_data:/var/lib/postgresql/data
    ports:
      - 5436:5432

  postgres-home-manager:
    image: postgres:12-alpine
    restart: unless-stopped
    container_name: postgres-home-manager
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: development_pass
      POSTGRES_DB: home-manager-api
    volumes:
      - home_manager_api_data:/var/lib/postgresql/data
    ports:
      - 5437:5432

  postgres-booking-manager:
    image: postgres:12-alpine
    restart: unless-stopped
    container_name: postgres-booking-manager
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: development_pass
      POSTGRES_DB: booking-manager-api
    volumes:
      - booking_manager_api_data:/var/lib/postgresql/data
    ports:
      - 5438:5432

volumes:
  auth_api_data: {}
  home_manager_api_data: {}
  booking_manager_api_data: {}
